apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: where-for-dinner-rmq-broker-config
  namespace: workloads
spec:
  rabbitmqClusterReference:
    name: msgbroker-where-for-dinner
    namespace: service-instances
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: where-for-dinner
  namespace: workloads
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: RabbitmqBrokerConfig
    name: where-for-dinner-rmq-broker-config
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    eventing.knative.dev/broker: where-for-dinner
  name: where-for-dinner-search-proc
  namespace: workloads
  annotations:
    rabbitmq.eventing.knative.dev/parallelism: "5"
spec:
  broker: where-for-dinner
  filter:
    attributes:
      source: /apis/v1/namespaces/workloads/rabbitmqsources/where-for-dinner-search-criteria-rabbit-source#where-for-dinner-search-criteria
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: where-for-dinner-search-proc
    uri: /processSearch
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    eventing.knative.dev/broker: where-for-dinner
  name: where-for-dinner-notify
  namespace: workloads
  annotations:
    rabbitmq.eventing.knative.dev/parallelism: "5"
spec:
  broker: where-for-dinner
  filter:
    attributes:
      source: http://spring.io/where-for-dinner-search-proc
      type: com.java.example.tanzu.wherefordinner.model.Availability
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: where-for-dinner-notify
    uri: /notifyAvailability
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    eventing.knative.dev/broker: where-for-dinner
  name: where-for-dinner-availability
  namespace: workloads
  annotations:
    rabbitmq.eventing.knative.dev/parallelism: "5"
spec:
  broker: where-for-dinner
  filter:
    attributes:
      source: http://spring.io/where-for-dinner-search-proc
      type: com.java.example.tanzu.wherefordinner.model.Availability
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: where-for-dinner-availability
    uri: /processAvailability
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  labels:
    eventing.knative.dev/SourceName: where-for-dinner-search-criteria-rabbit-source
  name: where-for-dinner-search-criteria
  namespace: workloads
spec:
  durable: true
  name: where-for-dinner-search-criteria
  rabbitmqClusterReference:
    name: msgbroker-where-for-dinner
    namespace: service-instances
  type: topic
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  labels:
    eventing.knative.dev/SourceName: where-for-dinner-search-criteria-rabbit-source
  name: where-for-dinner-search-criteria
  namespace: workloads
spec:
  durable: true
  autoDelete: false
  name: where-for-dinner-search-criteria
  rabbitmqClusterReference:
    name: msgbroker-where-for-dinner
    namespace: service-instances
  type: quorum
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  labels:
    eventing.knative.dev/SourceName: where-for-dinner-search-criteria-rabbit-source
  name: where-for-dinner-search-criteria
  namespace: workloads
spec:
  source: where-for-dinner-search-criteria
  destination: where-for-dinner-search-criteria
  destinationType: queue
  routingKey: '#'
  rabbitmqClusterReference:
    name: msgbroker-where-for-dinner
    namespace: service-instances
  vhost: /
---
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: where-for-dinner-search-criteria-rabbit-source
  namespace: workloads
spec:
  rabbitmqClusterReference:
    name: msgbroker-where-for-dinner
    namespace: service-instances
  rabbitmqResourcesConfig:
    predeclared: true
    parallelism: 5
    queueName: where-for-dinner-search-criteria
  sink:
    uri: http://where-for-dinner-broker-ingress.workloads.svc.cluster.local
